export interface LpiItem {
  aggregate_id: string;
  application_id: string;
  application_external_id: string;
  application_created_at: string;
  application_status: string;
  product_name: string;
  protocol_date: string | null;
  agg_gen_group_complience: string | null;
  customer_name: string | null;
  customer_mail: string | null;
  organization: string | null;
  customer_phone: string | null;
  customer_address: string | null;
  ekn: string | null;
  thickness: number | null;
  color: string | null;
  batch_number: string | null;
  sample_number: string | null;
  object_name: string | null;
  standard: string | null;
  target_comb_group: string | null;
  target_flam_group: string | null;
  target_prop_group: string | null;
  method_abbreviation: string | null;
  method_name: string | null;
  method_standard: string | null;
  agg_avg_smog_temp: string | null;
  agg_smog_group: string | null;
  agg_smog_complience: string | null;
  agg_mass_loss: string | null;
  agg_comb_time: string | null;
  agg_dam_length: string | null;
  agg_comb_bulb: string | null;
  agg_group_by_mass: string | null;
  agg_group_by_length: string | null;
  agg_croup_by_comb_time: string | null;
  agg_group_by_bulbe: string | null;
  agg_gen_group: string | null;
  agg_mass_complience: string | null;
  agg_complience_by_length: string | null;
  agg_complience_by_comb_time: string | null;
  agg_complience_by_bulbe: string | null;
  agg_additional_info_1: string | null;
  agg_critical_density_of_heat_flux: string | null;
  agg_calibration_flow: string | null;
  agg_calibration_length: string | null;
  agg_calibration_flow_csi: string | null;
  agg_calibration_flow_firelab: string | null;
  agg_calibration_flow_vniipo: string | null;
  mesure_data_lenght_rp: string | null;
  mesure_data_flow_rp: string | null;
  mesure_data_calibration_length_agg: string | null;
  mesure_data_lpi_flow_agg: string | null;
  mesure_data_rp1: string | null;
  mesure_data_rp2: string | null;
  mesure_data_rp3: string | null;
  mesure_data_rp4: string | null;
  source_series_count: number | null;
  source_series_range: string | null;
  calculation_type: string | null;
  result_data: string | null;
  completedLocally?: boolean;
  completedAt?: string;
  taskId?: string;
}
